/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLaunchRouteImport } from './routes/_authenticated/launch'
import { Route as AuthenticatedGenerationRouteImport } from './routes/_authenticated/generation'
import { Route as AuthenticatedEditRoomRouteImport } from './routes/_authenticated/edit-room'
import { Route as AuthenticatedDeliverablesRouteImport } from './routes/_authenticated/deliverables'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStoryboardIndexRouteImport } from './routes/_authenticated/storyboard.index'
import { Route as AuthenticatedScriptsIndexRouteImport } from './routes/_authenticated/scripts.index'
import { Route as AuthenticatedBriefsIndexRouteImport } from './routes/_authenticated/briefs.index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands.index'
import { Route as AuthenticatedAnglesIndexRouteImport } from './routes/_authenticated/angles.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedBriefsNewRouteImport } from './routes/_authenticated/briefs.new'
import { Route as AuthenticatedBrandsNewRouteImport } from './routes/_authenticated/brands.new'
import { Route as AuthenticatedBriefsBriefIdIndexRouteImport } from './routes/_authenticated/briefs.$briefId.index'
import { Route as AuthenticatedBrandsBrandIdIndexRouteImport } from './routes/_authenticated/brands.$brandId.index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedBriefsBriefIdEditRouteImport } from './routes/_authenticated/briefs.$briefId.edit'
import { Route as AuthenticatedBrandsBrandIdEditRouteImport } from './routes/_authenticated/brands.$brandId.edit'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaunchRoute = AuthenticatedLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerationRoute = AuthenticatedGenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditRoomRoute = AuthenticatedEditRoomRouteImport.update({
  id: '/edit-room',
  path: '/edit-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliverablesRoute =
  AuthenticatedDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryboardIndexRoute =
  AuthenticatedStoryboardIndexRouteImport.update({
    id: '/storyboard/',
    path: '/storyboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScriptsIndexRoute =
  AuthenticatedScriptsIndexRouteImport.update({
    id: '/scripts/',
    path: '/scripts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBriefsIndexRoute =
  AuthenticatedBriefsIndexRouteImport.update({
    id: '/briefs/',
    path: '/briefs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnglesIndexRoute =
  AuthenticatedAnglesIndexRouteImport.update({
    id: '/angles/',
    path: '/angles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBriefsNewRoute = AuthenticatedBriefsNewRouteImport.update({
  id: '/briefs/new',
  path: '/briefs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsNewRoute = AuthenticatedBrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefsBriefIdIndexRoute =
  AuthenticatedBriefsBriefIdIndexRouteImport.update({
    id: '/briefs/$briefId/',
    path: '/briefs/$briefId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsBrandIdIndexRoute =
  AuthenticatedBrandsBrandIdIndexRouteImport.update({
    id: '/brands/$brandId/',
    path: '/brands/$brandId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBriefsBriefIdEditRoute =
  AuthenticatedBriefsBriefIdEditRouteImport.update({
    id: '/briefs/$briefId/edit',
    path: '/briefs/$briefId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsBrandIdEditRoute =
  AuthenticatedBrandsBrandIdEditRouteImport.update({
    id: '/brands/$brandId/edit',
    path: '/brands/$brandId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/deliverables': typeof AuthenticatedDeliverablesRoute
  '/edit-room': typeof AuthenticatedEditRoomRoute
  '/generation': typeof AuthenticatedGenerationRoute
  '/launch': typeof AuthenticatedLaunchRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/qa': typeof AuthenticatedQaRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/briefs/new': typeof AuthenticatedBriefsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/angles/': typeof AuthenticatedAnglesIndexRoute
  '/brands/': typeof AuthenticatedBrandsIndexRoute
  '/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/storyboard/': typeof AuthenticatedStoryboardIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/briefs/$briefId/edit': typeof AuthenticatedBriefsBriefIdEditRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/brands/$brandId/': typeof AuthenticatedBrandsBrandIdIndexRoute
  '/briefs/$briefId/': typeof AuthenticatedBriefsBriefIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/deliverables': typeof AuthenticatedDeliverablesRoute
  '/edit-room': typeof AuthenticatedEditRoomRoute
  '/generation': typeof AuthenticatedGenerationRoute
  '/launch': typeof AuthenticatedLaunchRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/qa': typeof AuthenticatedQaRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/briefs/new': typeof AuthenticatedBriefsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/angles': typeof AuthenticatedAnglesIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/briefs': typeof AuthenticatedBriefsIndexRoute
  '/scripts': typeof AuthenticatedScriptsIndexRoute
  '/storyboard': typeof AuthenticatedStoryboardIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/briefs/$briefId/edit': typeof AuthenticatedBriefsBriefIdEditRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdIndexRoute
  '/briefs/$briefId': typeof AuthenticatedBriefsBriefIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/deliverables': typeof AuthenticatedDeliverablesRoute
  '/_authenticated/edit-room': typeof AuthenticatedEditRoomRoute
  '/_authenticated/generation': typeof AuthenticatedGenerationRoute
  '/_authenticated/launch': typeof AuthenticatedLaunchRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/brands/new': typeof AuthenticatedBrandsNewRoute
  '/_authenticated/briefs/new': typeof AuthenticatedBriefsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/angles/': typeof AuthenticatedAnglesIndexRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/_authenticated/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/_authenticated/storyboard/': typeof AuthenticatedStoryboardIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/_authenticated/briefs/$briefId/edit': typeof AuthenticatedBriefsBriefIdEditRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/brands/$brandId/': typeof AuthenticatedBrandsBrandIdIndexRoute
  '/_authenticated/briefs/$briefId/': typeof AuthenticatedBriefsBriefIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/deliverables'
    | '/edit-room'
    | '/generation'
    | '/launch'
    | '/library'
    | '/performance'
    | '/qa'
    | '/wallet'
    | '/brands/new'
    | '/briefs/new'
    | '/admin/'
    | '/angles/'
    | '/brands/'
    | '/briefs/'
    | '/scripts/'
    | '/storyboard/'
    | '/admin/users/$userId'
    | '/brands/$brandId/edit'
    | '/briefs/$briefId/edit'
    | '/admin/users/'
    | '/brands/$brandId/'
    | '/briefs/$briefId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/deliverables'
    | '/edit-room'
    | '/generation'
    | '/launch'
    | '/library'
    | '/performance'
    | '/qa'
    | '/wallet'
    | '/'
    | '/brands/new'
    | '/briefs/new'
    | '/admin'
    | '/angles'
    | '/brands'
    | '/briefs'
    | '/scripts'
    | '/storyboard'
    | '/admin/users/$userId'
    | '/brands/$brandId/edit'
    | '/briefs/$briefId/edit'
    | '/admin/users'
    | '/brands/$brandId'
    | '/briefs/$briefId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/deliverables'
    | '/_authenticated/edit-room'
    | '/_authenticated/generation'
    | '/_authenticated/launch'
    | '/_authenticated/library'
    | '/_authenticated/performance'
    | '/_authenticated/qa'
    | '/_authenticated/wallet'
    | '/_authenticated/'
    | '/_authenticated/brands/new'
    | '/_authenticated/briefs/new'
    | '/_authenticated/admin/'
    | '/_authenticated/angles/'
    | '/_authenticated/brands/'
    | '/_authenticated/briefs/'
    | '/_authenticated/scripts/'
    | '/_authenticated/storyboard/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/brands/$brandId/edit'
    | '/_authenticated/briefs/$briefId/edit'
    | '/_authenticated/admin/users/'
    | '/_authenticated/brands/$brandId/'
    | '/_authenticated/briefs/$briefId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launch': {
      id: '/_authenticated/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof AuthenticatedLaunchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generation': {
      id: '/_authenticated/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof AuthenticatedGenerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-room': {
      id: '/_authenticated/edit-room'
      path: '/edit-room'
      fullPath: '/edit-room'
      preLoaderRoute: typeof AuthenticatedEditRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliverables': {
      id: '/_authenticated/deliverables'
      path: '/deliverables'
      fullPath: '/deliverables'
      preLoaderRoute: typeof AuthenticatedDeliverablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboard/': {
      id: '/_authenticated/storyboard/'
      path: '/storyboard'
      fullPath: '/storyboard/'
      preLoaderRoute: typeof AuthenticatedStoryboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/': {
      id: '/_authenticated/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthenticatedScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs/': {
      id: '/_authenticated/briefs/'
      path: '/briefs'
      fullPath: '/briefs/'
      preLoaderRoute: typeof AuthenticatedBriefsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/angles/': {
      id: '/_authenticated/angles/'
      path: '/angles'
      fullPath: '/angles/'
      preLoaderRoute: typeof AuthenticatedAnglesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/briefs/new': {
      id: '/_authenticated/briefs/new'
      path: '/briefs/new'
      fullPath: '/briefs/new'
      preLoaderRoute: typeof AuthenticatedBriefsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/new': {
      id: '/_authenticated/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof AuthenticatedBrandsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs/$briefId/': {
      id: '/_authenticated/briefs/$briefId/'
      path: '/briefs/$briefId'
      fullPath: '/briefs/$briefId/'
      preLoaderRoute: typeof AuthenticatedBriefsBriefIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId/': {
      id: '/_authenticated/brands/$brandId/'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/briefs/$briefId/edit': {
      id: '/_authenticated/briefs/$briefId/edit'
      path: '/briefs/$briefId/edit'
      fullPath: '/briefs/$briefId/edit'
      preLoaderRoute: typeof AuthenticatedBriefsBriefIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId/edit': {
      id: '/_authenticated/brands/$brandId/edit'
      path: '/brands/$brandId/edit'
      fullPath: '/brands/$brandId/edit'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDeliverablesRoute: typeof AuthenticatedDeliverablesRoute
  AuthenticatedEditRoomRoute: typeof AuthenticatedEditRoomRoute
  AuthenticatedGenerationRoute: typeof AuthenticatedGenerationRoute
  AuthenticatedLaunchRoute: typeof AuthenticatedLaunchRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBrandsNewRoute: typeof AuthenticatedBrandsNewRoute
  AuthenticatedBriefsNewRoute: typeof AuthenticatedBriefsNewRoute
  AuthenticatedAnglesIndexRoute: typeof AuthenticatedAnglesIndexRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedBriefsIndexRoute: typeof AuthenticatedBriefsIndexRoute
  AuthenticatedScriptsIndexRoute: typeof AuthenticatedScriptsIndexRoute
  AuthenticatedStoryboardIndexRoute: typeof AuthenticatedStoryboardIndexRoute
  AuthenticatedBrandsBrandIdEditRoute: typeof AuthenticatedBrandsBrandIdEditRoute
  AuthenticatedBriefsBriefIdEditRoute: typeof AuthenticatedBriefsBriefIdEditRoute
  AuthenticatedBrandsBrandIdIndexRoute: typeof AuthenticatedBrandsBrandIdIndexRoute
  AuthenticatedBriefsBriefIdIndexRoute: typeof AuthenticatedBriefsBriefIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDeliverablesRoute: AuthenticatedDeliverablesRoute,
  AuthenticatedEditRoomRoute: AuthenticatedEditRoomRoute,
  AuthenticatedGenerationRoute: AuthenticatedGenerationRoute,
  AuthenticatedLaunchRoute: AuthenticatedLaunchRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBrandsNewRoute: AuthenticatedBrandsNewRoute,
  AuthenticatedBriefsNewRoute: AuthenticatedBriefsNewRoute,
  AuthenticatedAnglesIndexRoute: AuthenticatedAnglesIndexRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedBriefsIndexRoute: AuthenticatedBriefsIndexRoute,
  AuthenticatedScriptsIndexRoute: AuthenticatedScriptsIndexRoute,
  AuthenticatedStoryboardIndexRoute: AuthenticatedStoryboardIndexRoute,
  AuthenticatedBrandsBrandIdEditRoute: AuthenticatedBrandsBrandIdEditRoute,
  AuthenticatedBriefsBriefIdEditRoute: AuthenticatedBriefsBriefIdEditRoute,
  AuthenticatedBrandsBrandIdIndexRoute: AuthenticatedBrandsBrandIdIndexRoute,
  AuthenticatedBriefsBriefIdIndexRoute: AuthenticatedBriefsBriefIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
